name: Docker Image CI

on:
  push:
    branches: [ "test" ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: check out the repository
      uses: actions/checkout@v3
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Extract metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: |
          wilbax/icms-frontend:latest
        tags: |
          type=ref,event=pr
          type=sha,event=push

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: wilbax/icms-frontend:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to Elastic Beanstalk
      run: |
        zip application.zip -r ./Dockerrun.aws.json
        aws s3 cp application.zip s3://elasticbeanstalk-eu-north-1-637423287616/
        aws elasticbeanstalk create-application-version --application-name myICMS --version-label ${{ github.run_id }} --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-637423287616",S3Key="application.zip"
        aws elasticbeanstalk update-environment --application-name myICMS --environment-name MyICMS-env --version-label ${{ github.run_id }}