name: Docker Image CI

on:
  push:
    branches: [ "test" ]
  

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: check out the repository
      uses: actions/checkout@v3
      
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Extract metadata
      id: metadata
      uses: docker/metadata-action@v3
      with:
        images: |
          wilbax/icms-frontend:latest
        tags: |
          type=ref,event=pr
          type=sha,event=push

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: wilbax/icms-frontend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name iCMS-dashboard \
          --version-label 1.0 \
          --process \
          --source-bundle ImageURI=wilbax/icms-frontend:latest

        aws elasticbeanstalk update-environment \
          --application-name iCMS-dashboard \
          --environment-name iCMS-dashboard-env \
          --version-label 1.0
    